# Generated by Django 5.2.7 on 2025-10-30 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='alerts.employee')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.employee')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
